# Playbook sets up CentOs hosts
# to work in sg-lab.pl domain
#
# Created by Daniel Buk
#
# Requires:
# 
---
# configure DNS

- hosts: webservers

  tasks:
  - name: Include vars from dns_vars.yml
    include_vars:
      file: 'dns_vars.yml' 


  - name: Debug DNS vars
    debug:
      var: "{{ os_dns.dns_server }}"
      verbosity: 0
# configure NTP

# configure