# Playbook sets up CentOs hosts
# to work in sg-lab.pl domain
#
# Created by Daniel Buk
#
# Requires:
# 
---
# configure DNS

- hosts: AllManagedNoDNS

  tasks:
  - name: Include vars from dns_vars.yml
    include_vars:
      file: 'all_vars.yml' 

  - name: Configure hostname and domain name
    net_system:
      hostname: "{{ inventory_hostname_short }}"
      domain_name: sg-lab.pl

  - name: Configure name servers
    net_system:
      name_servers:
        - 10.49.23.11

# configure NTP

# configure