# Playbook to setup DNS server in sg-lab.pl domain
#
# Created by Daniel Buk
#
# Requires:
# bertvv.bind
---
- hosts: dns
  become: true

  tasks:
    - name: Include dns vars from dns_vars.yml
      include_vars:
        file: 'dns_vars.yml'     

    - name: Debug DNS vars
      debug:
        var: "{{ bind_zone_master_server_ip }}"
        verbosity: 3 
  
  roles:
    - bertvv.bind
