# Playbook used to prepare hosts to 
# be managed be Ansible with AWX
#
---
- hosts: "{{ survey_hosts }}"
  become: true
  roles:
    - prepare-os
  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
